---
- hosts: localhost 
  connection: local
  become: true

  tasks:
  - name: Install Packages
    package: 
      name:
      - htop
      - tmux
      - python-psutil
  - name: Copy WallPapers
    copy:
      src: files/Wallpapers/
      dest: /usr/share/backgrounds/
      owner: root
      group: root

  - name: Debug
    debug: var=ansible_env
  
  - name: Set default walpaper
    become_user: emb-shebshe
    dconf:
      key: "/org/mate/desktop/background/picture-filename"
      value: "'/usr/share/backgrounds/Anonymous-veni-vidi-vici.png'"
#    when: ansible_env['XDG_CURRENT_DESKTOP'] == 'MATE'
  
  - name: Set wallpaper position
    become_user: emb-shebshe
    dconf:
      key: "/org/mate/desktop/background/picture-options"
      value: "'zoom'"
